
name: nfc_passport_reader
description: A Dart port of NFCPassportReader
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  flutter_nfc: ^0.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0
